### ISSUE TITLE
julia 1.2 fails during setup

### ISSUE THREAD

**Issue by IanButterworth** [ararslan/CirrusCI.jl#1]
For matrix:
```
    matrix:
      - JULIA_VERSION: 1.0
      - JULIA_VERSION: 1.1
      - JULIA_VERSION: 1.2
      - JULIA_VERSION: nightly
```
1.2 fails with:
```
sh -c "$(fetch https://raw.githubusercontent.com/ararslan/CirrusCI.jl/master/bin/install.sh -o -)"
-                                                     4669  B   33 MBps    00s
Updating FreeBSD repository catalogue...
Fetching meta.txz: . done
Fetching packagesite.txz: .......... done
Processing entries: .......... done
FreeBSD repository update completed. 31672 packages processed.
All repositories are up to date.
The following 1 package(s) will be affected (of 0 checked):
Installed packages to be UPGRADED:
	curl: 7.62.0 -> 7.65.0_2
Number of packages to be upgraded: 1
1 MiB to be downloaded.
[1/1] Fetching curl-7.65.0_2.txz: .......... done
Checking integrity... done (0 conflicting)
[1/1] Upgrading curl from 7.62.0 to 7.65.0_2...
[1/1] Extracting curl-7.65.0_2: .......... done
tar: Error opening archive: Unrecognized archive format
```
re. https://github.com/fhs/ZipFile.jl/pull/54
