### ISSUE TITLE
Show example with allowed failure

### ISSUE THREAD

**Issue by dpo** [ararslan/CirrusCI.jl#2]
Thank you for this package! Would you mind showing an example where the nightly build is allowed to fail? This syntax doesn't seem to do it: https://github.com/JuliaSmoothOptimizers/SolverBenchmark.jl/pull/34/files#diff-0f7067c31caedf7df2739c9b07efa122R12

Thanks!

**Comment by ararslan** [comment]
Hm, according to [the Cirrus documentation](https://cirrus-ci.org/guide/writing-tasks/#failure-toleration), I would have expected that syntax to work. I'll look into this and include an example once I figure it out.

**Comment by dpo** [comment]
In the meantime, we found out that the syntax is
```yml
freebsd_instance:
  image: freebsd-12-0-release-amd64
task:
  name: FreeBSD
  env:
    matrix:
      - JULIA_VERSION: 1.0
      - JULIA_VERSION: 1.1
      - JULIA_VERSION: 1.2
      - JULIA_VERSION: 1.3
      - JULIA_VERSION: nightly
  allow_failures: $JULIA_VERSION == 'nightly'
  install_script:
    - sh -c "$(fetch https://raw.githubusercontent.com/ararslan/CirrusCI.jl/master/bin/install.sh -o -)"
  build_script:
    - cirrusjl build
  test_script:
    - cirrusjl test
```
It would be useful to see that example in your README. Happy to submit the PR if it helps.
